/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Admin;

/**
 *
 * @author PC
 */
public class PrintSalesDetails extends javax.swing.JFrame {

    /** Creates new form PrintSalesDetails */
    public PrintSalesDetails() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        page = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        prodname = new javax.swing.JLabel();
        cat = new javax.swing.JLabel();
        quansold = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        sale_id = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        expire = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(89, 196, 19));
        setMaximumSize(new java.awt.Dimension(550, 650));
        setMinimumSize(new java.awt.Dimension(550, 650));
        setPreferredSize(new java.awt.Dimension(550, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        page.setBackground(new java.awt.Color(255, 255, 255));
        page.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(89, 196, 19), 2, true));
        page.setMaximumSize(new java.awt.Dimension(500, 600));
        page.setMinimumSize(new java.awt.Dimension(500, 600));
        page.setPreferredSize(new java.awt.Dimension(500, 600));
        page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Category:");
        page.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 90, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Product Name:");
        page.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Quantity Sold:");
        page.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 130, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Price:");
        page.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 90, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Total:");
        page.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 90, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Date:");
        page.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 90, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Time:");
        page.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 90, -1));

        prodname.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        prodname.setText("Product Name");
        page.add(prodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 170, -1));

        cat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cat.setText("Category");
        page.add(cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 170, -1));

        quansold.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        quansold.setText("Quantity Sold");
        page.add(quansold, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 170, -1));

        price.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        price.setText("Price");
        page.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 170, -1));

        total.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        total.setText("Total");
        page.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 170, -1));

        date.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        date.setText("Date");
        page.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 170, -1));

        time.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        time.setText("Time");
        page.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 170, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Sale Id:");
        page.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        sale_id.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sale_id.setText("Sale Id");
        page.add(sale_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 170, -1));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Expire Date:");
        page.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 110, -1));

        expire.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        expire.setText("Expire Date");
        page.add(expire, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 170, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(89, 196, 19));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Posify");
        page.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 500, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("TRANSACTION DETAILS");
        page.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 500, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(89, 196, 19));
        jLabel1.setText("_______________________________________________________");
        page.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(89, 196, 19));
        jLabel2.setText("_______________________________________________________");
        page.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        getContentPane().add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintSalesDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintSalesDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintSalesDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintSalesDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintSalesDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel cat;
    public javax.swing.JLabel date;
    public javax.swing.JLabel expire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    public javax.swing.JPanel page;
    public javax.swing.JLabel price;
    public javax.swing.JLabel prodname;
    public javax.swing.JLabel quansold;
    public javax.swing.JLabel sale_id;
    public javax.swing.JLabel time;
    public javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables

}
